version: '3.7'
services:
  ruby:
    image: "${PROJECT_NAME}/ruby:init"
    container_name: ${PROJECT_NAME}-ruby
    build:
      context: ./
      dockerfile: ./containers/ruby/Dockerfile
      target: init
    volumes:
      - ${APP_PATH}:/app:cached
